server.port=${PORT:8080}
server.address=0.0.0.0
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Security Config (Dummy keys for now)
guardian.jwt.secret=${GUARDIAN_JWT_SECRET:9a4f4e354567f123c88355aa7de9fd267a544567f123c88355aa7de9fd267a54}
guardian.jwt.expiration=86400000

# Configuración de Zona Horaria (Colombia)
spring.jackson.time-zone=America/Bogota
spring.jpa.properties.hibernate.jdbc.time_zone=America/Bogota
