spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/guardian_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin123}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Security Config (Dummy keys for now)
guardian.jwt.secret=9a4f4e354567f123c88355aa7de9fd267a544567f123c88355aa7de9fd267a54
guardian.jwt.expiration=86400000
